# Generated by Django 5.0 on 2025-09-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('total_complaints', models.IntegerField(default=0)),
                ('pending_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('avg_resolution_time_days', models.FloatField(default=0.0)),
                ('total_feedback', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('active_staff_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date', 'department__name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaints_created', models.IntegerField(default=0)),
                ('complaints_updated', models.IntegerField(default=0)),
                ('comments_added', models.IntegerField(default=0)),
                ('withdrawals_submitted', models.IntegerField(default=0)),
                ('feedback_submitted', models.IntegerField(default=0)),
                ('login_count', models.IntegerField(default=0)),
                ('total_session_time_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_complaints', models.IntegerField(default=0)),
                ('pending_complaints', models.IntegerField(default=0)),
                ('in_progress_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('rejected_complaints', models.IntegerField(default=0)),
                ('not_resolved_complaints', models.IntegerField(default=0)),
                ('closed_complaints', models.IntegerField(default=0)),
                ('new_complaints_today', models.IntegerField(default=0)),
                ('total_withdrawals', models.IntegerField(default=0)),
                ('pending_withdrawals', models.IntegerField(default=0)),
                ('approved_withdrawals', models.IntegerField(default=0)),
                ('rejected_withdrawals', models.IntegerField(default=0)),
                ('new_withdrawals_today', models.IntegerField(default=0)),
                ('total_feedback', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('new_feedback_today', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('avg_resolution_time_days', models.FloatField(default=0.0)),
                ('avg_response_time_hours', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_date'], name='analytics_a_snapsho_bc6626_idx')],
            },
        ),
    ]
