# Generated by Django 5.0 on 2025-09-20 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentanalytics',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
        migrations.AddField(
            model_name='useractivitysummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='departmentanalytics',
            index=models.Index(fields=['department', 'snapshot_date'], name='analytics_d_departm_05e077_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentanalytics',
            unique_together={('department', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='useractivitysummary',
            index=models.Index(fields=['user', 'date'], name='analytics_u_user_id_34e6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitysummary',
            index=models.Index(fields=['date'], name='analytics_u_date_a871af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useractivitysummary',
            unique_together={('user', 'date')},
        ),
    ]
