# Generated by Django 5.0 on 2025-09-20 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('course_withdrawal', 'Course Withdrawal'), ('semester_withdrawal', 'Semester Withdrawal'), ('program_withdrawal', 'Program Withdrawal'), ('leave_of_absence', 'Leave of Absence'), ('transfer_request', 'Transfer Request'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('response', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='withdrawals/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_number'], name='withdrawals_request_3f058d_idx'), models.Index(fields=['status'], name='withdrawals_status_00b1c5_idx'), models.Index(fields=['submitted_by'], name='withdrawals_submitt_c240bd_idx'), models.Index(fields=['type'], name='withdrawals_type_ccf90d_idx')],
            },
        ),
    ]
