# Generated by Django 5.0 on 2025-09-20 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintfeedback',
            name='forwarded_to',
            field=models.ManyToManyField(blank=True, help_text='Users who received this feedback (Head, VC, Admin)', related_name='received_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintfeedback',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.complaintfeedback'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='responded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='complaintfeedback',
            index=models.Index(fields=['complaint'], name='feedback_co_complai_97c635_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintfeedback',
            index=models.Index(fields=['submitted_by'], name='feedback_co_submitt_67c7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintfeedback',
            index=models.Index(fields=['rating'], name='feedback_co_rating_94dd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintfeedback',
            index=models.Index(fields=['submitted_at'], name='feedback_co_submitt_935261_idx'),
        ),
    ]
