# Generated by Django 5.0 on 2025-09-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('complaint_created', 'Complaint Created'), ('complaint_forwarded', 'Complaint Forwarded'), ('complaint_status_changed', 'Complaint Status Changed'), ('comment_added', 'Comment Added'), ('reply_added', 'Reply Added'), ('withdrawal_submitted', 'Withdrawal Request Submitted'), ('withdrawal_reviewed', 'Withdrawal Request Reviewed'), ('feedback_submitted', 'Feedback Submitted'), ('feedback_response', 'Feedback Response'), ('system', 'System Notification')], default='system', max_length=25)),
                ('link', models.URLField(blank=True, help_text='Link to related page', null=True)),
                ('related_complaint_id', models.IntegerField(blank=True, null=True)),
                ('related_withdrawal_id', models.IntegerField(blank=True, null=True)),
                ('related_feedback_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_complaint_updates', models.BooleanField(default=True)),
                ('email_withdrawal_updates', models.BooleanField(default=True)),
                ('email_feedback_updates', models.BooleanField(default=True)),
                ('email_system_updates', models.BooleanField(default=True)),
                ('app_complaint_updates', models.BooleanField(default=True)),
                ('app_withdrawal_updates', models.BooleanField(default=True)),
                ('app_feedback_updates', models.BooleanField(default=True)),
                ('app_system_updates', models.BooleanField(default=True)),
                ('email_digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='immediate', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
